book_guise_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookguise.urls'))
]

book_guise_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookguise.urls'))
]

bookguise/urls.py
from django.urls import path
from . import views

app_name = "bookguise"
urlpatterns = [
    path('', views.index, name='index'),
    path('result', views.fave_book_search, name='fave_book_search')
]

bookguise/models/models.py
from django.db import models

# Create your models here.

bookguise/views/fave_book_search.py
import requests
from django.shortcuts import render
from bookguise.fave_book_search import fave_book
from bookguise.suggested_book_builder import Suggested_Book


def fave_book_search(request):
    fave_result = []

    if request.method == 'POST':
        title_input = request.POST['title_input'].strip()

        if title_input:
            fave_result = fave_book(title_input)
            suggested_books = list()

            if not isinstance(fave_result, str):
                for book in fave_result["similar_titles"]:
                    suggested_book_result = Suggested_Book(book)
                    suggested_books.append(suggested_book_result)
                print(suggested_books)

    return render(request, 'bookguise/index.html', {'fave_result': fave_result, 'suggested_books': suggested_books})

bookguise/views/index.py
from django.shortcuts import render


def index(request):
    return render(request, 'bookguise/index.html')

bookguise/templates/bookguise/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BookGuise, the masquerade party for books</title>
    <link href="https://fonts.googleapis.com/css?family=Lato|Old+Standard+TT" rel="stylesheet">
    <link rel="stylesheet" href="../../static/bookguise/main.css">
</head>

<body>
    {% block content %}{% include 'bookguise/search_bar.html' %}{% endblock %}
</body>

</html>

bookguise/templates/bookguise/search_bar.html
{% block content %}
<div class="top">

    <h1 class="centered">Welcome to BookGuise</h1>
    <p class="centered">What's the title of your favorite book?</p>
</div>
<div class="search-grid">
    <div class="search-side centered">
        <form id="fave_book_search_form" method="post" action="{% url 'bookguise:fave_book_search' %}">
            {% csrf_token %}
            <input type="text" size="50" name="title_input" value="" id="title_input" />
            <input type="submit" value="Search" name="submit" />
            <br />
        </form>
    </div>

    <div class="result-side">
        {% if fave_result %}
        {% if fave_result.title %}

        <h2 class="centered">Your Favorite Book:</h2>
        <div class="wrapper fave-result">
            <div class="wrapper centered fave-book">
                <div class="wrapper centered fave-img">
                    <a href="{{fave_result.gr_link}}" target="_blank">
                        <img src="{{fave_result.cover}}" alt="Favorite Book Cover"></a>
                </div>
                <div class="wrapper">
                    <div class="fiddly">
                        <p class="fave-text"><a href="{{fave_result.gr_link}}" target="_blank">{{fave_result.title}}</a></p>
                        <p class="fave-text">{{fave_result.author}}</p>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <div>
            <p class="centered">{{fave_result.unicorn_message}}</p>
            <p class="centered">Please join the masquerade by searching again!</p>
        </div>
        {% endif %}
        {% endif %}
    </div>
</div>
{% if suggested_books %}
<h2 class="centered">Your Mysterious Recommendations:</h2>
<div class="mystery-books grid centered">
    {% for book in suggested_books %}
    <div class="wrapper card column">
        <a href="{{book.gr_link}}" target="_blank">
            <div class="wrapper centered book-bg" style="background-color:{{book.bg_color}}">
                <img class="book-img centered" src="../../static/img/{{book.bg_mask}}" alt="Mask for the mysterious book">
            </div>
        </a>
        <div class="wrapper column">
            <h4 class="centered">Published in {{book.publication_year}}</h4>
            <hr width="50%">
            {% if book.lt_haiku_summaries %}
            <h4 class="centered">Haiku Summaries:</h4>
            {% for haiku in book.lt_haiku_summaries %}
            <p class="centered">{{haiku}}</p>
            <hr width="50%">
            {% endfor %}

            {% endif %}
            {% if book.keywords %}
            <h4 class="centered">Keywords:</h4>
            <p>
                {% for keyword in book.keywords %}
                {{keyword}},
                {% endfor %}
            </p>
            {% else %}
            <p>No keywords?! What a mysterious book!</p>
            {% endif %}
        </div>

    </div>
    {% endfor %}
</div>
{% endif %}


{% endblock %}